# Generated by Django 4.2.5 on 2024-01-09 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("grader", "0007_auto_20180812_1555"),
    ]

    operations = [
        migrations.AddField(
            model_name="essay",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="essay",
            name="matric_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="essay",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
